### ISSUE TITLE
where is the dataset for model

### ISSUE THREAD

**Issue by ghost** [rishabhiitbhu/code_for_fun#2]
Actually i am new to this. I was trying to implement this concept in form of an android app. For that we need to write this model using tensor flow and then save the model to be able to use it in our app. For training the model we would require dataset and with appropriate label on it.  I tried but couldn't figure out that where exactly is training and test data in your project. Could you please guide me on this.

**Comment by pyaf** [comment]
you can create your own dataset, no?
Why do you think I'll share my dataset (my whatsapp images)? :crying_cat_face:
